# Importing the Libraries

In [1]:
import numpy as np 
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

# Part 1 - Data Preprocessing

# Importing the Data set

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Encoding Categorical data

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
print(y)

[1 0 1 ... 1 1 0]


## One Hot Encoding The "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[("encoder", OneHotEncoder(),[1])],remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [12]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Feature Scalling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [14]:
print(x)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


## Splitting the dataset into the Training set and test set

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2,random_state=0)

## Part 2. Building the ANN

### Initializing the ANN

In [16]:
ann = tf.keras.models.Sequential()

### Adding the input layer and first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the Second Hidden Layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the Outer Layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

### Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

### Training the ANN on the Training set

In [21]:
ann.fit(x_train,y_train,batch_size=128,epochs=100)

Epoch 1/100
63/63 [==============================] - 1s 2ms/step - loss: 0.7938 - accuracy: 0.4873
Epoch 2/100
63/63 [==============================] - 0s 2ms/step - loss: 0.6035 - accuracy: 0.7111
Epoch 3/100
63/63 [==============================] - 0s 2ms/step - loss: 0.5433 - accuracy: 0.7680
Epoch 4/100
63/63 [==============================] - 0s 2ms/step - loss: 0.5145 - accuracy: 0.7885
Epoch 5/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4945 - accuracy: 0.7979
Epoch 6/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4792 - accuracy: 0.8020
Epoch 7/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4673 - accuracy: 0.8045
Epoch 8/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4577 - accuracy: 0.8069
Epoch 9/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4500 - accuracy: 0.8084
Epoch 10/100
63/63 [==============================] - 0s 2ms/step - loss: 0.4437 - accuracy: 0.8112
Epoch 11/

## Part 3. Making The Predictions and evaluating the Model

### Predicting the Test sets results

In [22]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1518   77]
 [ 210  195]]
